import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import ProductManagement from "./components/productManagment";
import AdminPage from "./components/AdminPage";
// import FirstDealer from "./components/FirstDealer";
import LandingPage from "./components/landingpage";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LandingPage/>
        {/* <FirstDealer/> */}
        <AdminPage/>
        {/* <ProductManagement/> */}
        {children}
      </body>
    </html>
  );
}
